"""empty message

Revision ID: 244bda4a3c84
Revises: afcc227a8926
Create Date: 2024-03-17 14:59:16.648208

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '244bda4a3c84'
down_revision = 'afcc227a8926'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_info', schema=None) as batch_op:
        batch_op.add_column(sa.Column('organisation_2', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('organisation_3', sa.String(), nullable=True))
        batch_op.create_unique_constraint("unique_orcid", ['orcid'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_info', schema=None) as batch_op:
        batch_op.drop_constraint("unique_orcid", type_='unique')
        batch_op.drop_column('organisation_3')
        batch_op.drop_column('organisation_2')

    # ### end Alembic commands ###
