"""empty message

Revision ID: 47abc2e24693
Revises: affa9a9fb156
Create Date: 2024-03-15 13:53:15.193338

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '47abc2e24693'
down_revision = 'affa9a9fb156'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_info', schema=None) as batch_op:
        batch_op.add_column(sa.Column('orcid', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_info', schema=None) as batch_op:
        batch_op.drop_column('orcid')

    # ### end Alembic commands ###
