"""empty message

Revision ID: 8008a094c567
Revises: dc0626325afa
Create Date: 2024-04-12 09:56:43.768300

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "8008a094c567"
down_revision = "dc0626325afa"
branch_labels = None
depends_on = None


def upgrade():
    op.execute("create schema if not exists edit")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "references",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("doi", sa.String(), nullable=True),
        sa.Column("pubmed", sa.String(), nullable=True),
        sa.Column("title", sa.String(), nullable=True),
        sa.Column("authors", sa.String(), nullable=True),
        sa.Column("year", sa.Integer(), nullable=True),
        sa.Column("journal", sa.String(), nullable=True),
        sa.Column("url", sa.String(), nullable=True),
        sa.Column("patent", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        schema="edit",
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("references", schema="edit")
    # ### end Alembic commands ###
    op.execute("drop schema edit")
