"""empty message

Revision ID: ab82488f99ba
Revises: 8008a094c567
Create Date: 2024-04-12 14:07:45.760624

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ab82488f99ba'
down_revision = '8008a094c567'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('entries',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('identifier', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='edit'
    )
    op.create_table('entry_references',
    sa.Column('entry_id', sa.Integer(), nullable=False),
    sa.Column('reference_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['entry_id'], ['edit.entries.id'], ),
    sa.ForeignKeyConstraint(['reference_id'], ['edit.references.id'], ),
    sa.PrimaryKeyConstraint('entry_id', 'reference_id'),
    schema='edit'
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('entry_references', schema='edit')
    op.drop_table('entries', schema='edit')
    # ### end Alembic commands ###
