"""empty message

Revision ID: ba2bef42675f
Revises: cc97f97c2669
Create Date: 2024-05-07 09:40:39.764762

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ba2bef42675f'
down_revision = 'cc97f97c2669'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('substrates',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('fullname', sa.String(), nullable=True),
    sa.Column('structure', sa.String(), nullable=False),
    sa.Column('proteinogenic', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='edit'
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('substrates', schema='edit')
    # ### end Alembic commands ###
