"""empty message

Revision ID: cc97f97c2669
Revises: ab82488f99ba
Create Date: 2024-04-18 13:50:20.034368

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cc97f97c2669'
down_revision = 'ab82488f99ba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('npatlas',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('npaid', sa.String(), nullable=False),
    sa.Column('compound_names', sa.String(), nullable=False),
    sa.Column('compound_molecular_formula', sa.String(), nullable=False),
    sa.Column('compound_accurate_mass', sa.Float(), nullable=False),
    sa.Column('compound_inchi', sa.String(), nullable=False),
    sa.Column('compound_inchikey', sa.String(), nullable=False),
    sa.Column('compound_smiles', sa.String(), nullable=False),
    sa.Column('npatlas_url', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='edit'
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('npatlas', schema='edit')
    # ### end Alembic commands ###
