"""empty message

Revision ID: e3dc87b2eb23
Revises: 244bda4a3c84
Create Date: 2024-03-17 19:17:11.331785

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'e3dc87b2eb23'
down_revision = '244bda4a3c84'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('roles',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('slug', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug'),
    schema='auth'
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('_password', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    schema='auth'
    )
    op.create_table('tokens',
    sa.Column('token_id', sa.String(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('purpose', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['auth.users.id'], ),
    sa.PrimaryKeyConstraint('token_id'),
    schema='auth'
    )
    op.create_table('user_info',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('alias', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('call_name', sa.String(), nullable=False),
    sa.Column('organisation', sa.String(), nullable=False),
    sa.Column('organisation_2', sa.String(), nullable=True),
    sa.Column('organisation_3', sa.String(), nullable=True),
    sa.Column('orcid', sa.String(), nullable=True),
    sa.Column('public', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['auth.users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('alias'),
    sa.UniqueConstraint('orcid'),
    schema='auth'
    )
    op.create_table('user_roles',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['auth.roles.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['auth.users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'role_id'),
    schema='auth'
    )
    op.drop_table('user_roles')
    op.drop_table('user_info')
    op.drop_table('tokens')
    op.drop_table('roles')
    op.drop_table('users')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tokens',
    sa.Column('token_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('purpose', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='tokens_user_id_fkey'),
    sa.PrimaryKeyConstraint('token_id', name='tokens_pkey')
    )
    op.create_table('user_info',
    sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('alias', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('call_name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('organisation', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('public', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('orcid', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('organisation_2', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('organisation_3', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['id'], ['users.id'], name='user_info_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='user_info_pkey'),
    sa.UniqueConstraint('alias', name='user_info_alias_key'),
    sa.UniqueConstraint('orcid', name='unique_orcid')
    )
    op.create_table('user_roles',
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('role_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], name='user_roles_role_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='user_roles_user_id_fkey'),
    sa.PrimaryKeyConstraint('user_id', 'role_id', name='user_roles_pkey')
    )
    op.create_table('roles',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('slug', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='roles_pkey'),
    sa.UniqueConstraint('slug', name='roles_slug_key')
    )
    op.create_table('users',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('_password', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('active', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='users_pkey'),
    sa.UniqueConstraint('email', name='users_email_key')
    )
    op.drop_table('user_roles', schema='auth')
    op.drop_table('user_info', schema='auth')
    op.drop_table('tokens', schema='auth')
    op.drop_table('users', schema='auth')
    op.drop_table('roles', schema='auth')
    # ### end Alembic commands ###
